//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Tata.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class alarm_report
    {
        public int reportid { get; set; }
        public Nullable<int> slno { get; set; }
        public string alarmno { get; set; }
        public string alarmdescn { get; set; }
        public Nullable<System.DateTime> alarmdatetime { get; set; }
    }
}
