//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Tata.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class alldatatype
    {
        public int AllDataTypesID { get; set; }
        public string StringType { get; set; }
        public Nullable<int> IntType { get; set; }
        public Nullable<System.DateTime> DateTimeType { get; set; }
    }
}
