//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Tata.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class day_st_end_time
    {
        public int DayID { get; set; }
        public System.TimeSpan DayStart { get; set; }
        public System.TimeSpan DayEnd { get; set; }
    }
}
