//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Tata.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class parametermaster_view
    {
        public sbyte ParameterID { get; set; }
        public sbyte SetupTime { get; set; }
        public sbyte OperatingTime { get; set; }
        public sbyte PowerOnTime { get; set; }
        public sbyte PartsCount { get; set; }
        public sbyte InsertedOn { get; set; }
        public sbyte MachineID { get; set; }
        public sbyte Shift { get; set; }
        public sbyte CorrectedDate { get; set; }
        public sbyte InsertedOnTime { get; set; }
    }
}
