//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Tata.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class program_temp
    {
        public int ProgramID { get; set; }
        public string ProgramData { get; set; }
        public System.DateTime ProgramDateTime { get; set; }
        public Nullable<int> MachineID { get; set; }
    }
}
