//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Tata.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class mazakdaqEntities : DbContext
    {
        public mazakdaqEntities()
            : base("name=mazakdaqEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<alarm_history_master> alarm_history_master { get; set; }
        public DbSet<alarm_master> alarm_master { get; set; }
        public DbSet<alarm_report> alarm_report { get; set; }
        public DbSet<automaticjobcard> automaticjobcards { get; set; }
        public DbSet<book> books { get; set; }
        public DbSet<code_master> code_master { get; set; }
        public DbSet<cutting_time_report> cutting_time_report { get; set; }
        public DbSet<cutting_time_report_pdf> cutting_time_report_pdf { get; set; }
        public DbSet<day_st_end_time> day_st_end_time { get; set; }
        public DbSet<frommail> frommails { get; set; }
        public DbSet<handle_no_ping> handle_no_ping { get; set; }
        public DbSet<jobcard_details> jobcard_details { get; set; }
        public DbSet<machine_master> machine_master { get; set; }
        public DbSet<mailmaster> mailmasters { get; set; }
        public DbSet<mailmasterprogesc> mailmasterprogescs { get; set; }
        public DbSet<main_time_rep> main_time_rep { get; set; }
        public DbSet<message_code_master> message_code_master { get; set; }
        public DbSet<message_history_master> message_history_master { get; set; }
        public DbSet<opcuttimereport> opcuttimereports { get; set; }
        public DbSet<opcuttimereport_pdf> opcuttimereport_pdf { get; set; }
        public DbSet<operating_time_report> operating_time_report { get; set; }
        public DbSet<operating_time_report_pdf> operating_time_report_pdf { get; set; }
        public DbSet<operationlog> operationlogs { get; set; }
        public DbSet<parameter> parameters { get; set; }
        public DbSet<parameters_master> parameters_master { get; set; }
        public DbSet<pcb> pcbs { get; set; }
        public DbSet<pcb_details> pcb_details { get; set; }
        public DbSet<pcb_parameters> pcb_parameters { get; set; }
        public DbSet<pcbdaq> pcbdaqs { get; set; }
        public DbSet<pcbdaqin_tbl> pcbdaqin_tbl { get; set; }
        public DbSet<pcbdps_master> pcbdps_master { get; set; }
        public DbSet<program_master> program_master { get; set; }
        public DbSet<program_temp> program_temp { get; set; }
        public DbSet<recipientmailid> recipientmailids { get; set; }
        public DbSet<role_master> role_master { get; set; }
        public DbSet<shift_master> shift_master { get; set; }
        public DbSet<tbl_autoreport_log> tbl_autoreport_log { get; set; }
        public DbSet<tbl_autoreportbasedon> tbl_autoreportbasedon { get; set; }
        public DbSet<tbl_autoreportsetting> tbl_autoreportsetting { get; set; }
        public DbSet<tbl_autoreporttime> tbl_autoreporttime { get; set; }
        public DbSet<tbl_multiwoselection> tbl_multiwoselection { get; set; }
        public DbSet<tbl_reportmaster> tbl_reportmaster { get; set; }
        public DbSet<tblactivitylog> tblactivitylogs { get; set; }
        public DbSet<tblapp_paths> tblapp_paths { get; set; }
        public DbSet<tblbreakdown> tblbreakdowns { get; set; }
        public DbSet<tblbreakdowncode> tblbreakdowncodes { get; set; }
        public DbSet<tblcell> tblcells { get; set; }
        public DbSet<tblcustomer> tblcustomers { get; set; }
        public DbSet<tbldailyprodstatu> tbldailyprodstatus { get; set; }
        public DbSet<tbldailyprodstatushi> tbldailyprodstatushis { get; set; }
        public DbSet<tbldaytiming> tbldaytimings { get; set; }
        public DbSet<tblddl> tblddls { get; set; }
        public DbSet<tbldowntimecategory> tbldowntimecategories { get; set; }
        public DbSet<tbldowntimedetail> tbldowntimedetails { get; set; }
        public DbSet<tblemailescalation> tblemailescalations { get; set; }
        public DbSet<tblemailreporttype> tblemailreporttypes { get; set; }
        public DbSet<tblendcode> tblendcodes { get; set; }
        public DbSet<tblescalationlog> tblescalationlogs { get; set; }
        public DbSet<tblgenericworkcode> tblgenericworkcodes { get; set; }
        public DbSet<tblgenericworkentry> tblgenericworkentries { get; set; }
        public DbSet<tblhmiscreen> tblhmiscreens { get; set; }
        public DbSet<tblholdcode> tblholdcodes { get; set; }
        public DbSet<tbllivedailyprodstatu> tbllivedailyprodstatus { get; set; }
        public DbSet<tbllivehmiscreen> tbllivehmiscreens { get; set; }
        public DbSet<tbllivehmiscreenrep> tbllivehmiscreenreps { get; set; }
        public DbSet<tbllivelossofentry> tbllivelossofentries { get; set; }
        public DbSet<tbllivelossofentryrep> tbllivelossofentryreps { get; set; }
        public DbSet<tbllivemanuallossofentryrep> tbllivemanuallossofentryreps { get; set; }
        public DbSet<tbllivemode> tbllivemodes { get; set; }
        public DbSet<tbllivemodedb> tbllivemodedbs { get; set; }
        public DbSet<tbllivemultiwoselection> tbllivemultiwoselections { get; set; }
        public DbSet<tbllossescode> tbllossescodes { get; set; }
        public DbSet<tbllossofentry> tbllossofentries { get; set; }
        public DbSet<tblmachine_master> tblmachine_master { get; set; }
        public DbSet<tblmachineallocation> tblmachineallocations { get; set; }
        public DbSet<tblmachinecategory> tblmachinecategories { get; set; }
        public DbSet<tblmachinedetail> tblmachinedetails { get; set; }
        public DbSet<tblmachinedetailsnew> tblmachinedetailsnews { get; set; }
        public DbSet<tblmailid> tblmailids { get; set; }
        public DbSet<tblmanuallossofentry> tblmanuallossofentries { get; set; }
        public DbSet<tblmasterparts_st_sw> tblmasterparts_st_sw { get; set; }
        public DbSet<tblmimic> tblmimics { get; set; }
        public DbSet<tblmode> tblmodes { get; set; }
        public DbSet<tblmodulehelper> tblmodulehelpers { get; set; }
        public DbSet<tblmodulemaster> tblmodulemasters { get; set; }
        public DbSet<tblmultipleworkorder> tblmultipleworkorders { get; set; }
        public DbSet<tblnetworkdetailsforddl> tblnetworkdetailsforddls { get; set; }
        public DbSet<tbloeedashboardfinalvariable> tbloeedashboardfinalvariables { get; set; }
        public DbSet<tbloeedashboardvariable> tbloeedashboardvariables { get; set; }
        public DbSet<tbloeedashboardvariablestoday> tbloeedashboardvariablestodays { get; set; }
        public DbSet<tblpart> tblparts { get; set; }
        public DbSet<tblpartwisesp> tblpartwisesps { get; set; }
        public DbSet<tblpartwiseworkcenter> tblpartwiseworkcenters { get; set; }
        public DbSet<tblplannedbreak> tblplannedbreaks { get; set; }
        public DbSet<tblplant> tblplants { get; set; }
        public DbSet<tblpriorityalarm> tblpriorityalarms { get; set; }
        public DbSet<tblreportholder> tblreportholders { get; set; }
        public DbSet<tblroleplaymaster> tblroleplaymasters { get; set; }
        public DbSet<tblrole> tblroles { get; set; }
        public DbSet<tblsendermailid> tblsendermailids { get; set; }
        public DbSet<tblshift_breaks> tblshift_breaks { get; set; }
        public DbSet<tblshift_mstr> tblshift_mstr { get; set; }
        public DbSet<tblshiftdetail> tblshiftdetails { get; set; }
        public DbSet<tblshiftdetails_machinewise> tblshiftdetails_machinewise { get; set; }
        public DbSet<tblshiftmethod> tblshiftmethods { get; set; }
        public DbSet<tblshiftplanner> tblshiftplanners { get; set; }
        public DbSet<tblshop> tblshops { get; set; }
        public DbSet<tbltosapfilepath> tbltosapfilepaths { get; set; }
        public DbSet<tbltosapshopname> tbltosapshopnames { get; set; }
        public DbSet<tblunit> tblunits { get; set; }
        public DbSet<tbluser> tblusers { get; set; }
        public DbSet<tblwolossess> tblwolossesses { get; set; }
        public DbSet<tblworeport> tblworeports { get; set; }
        public DbSet<user_master> user_master { get; set; }
        public DbSet<main_time_view> main_time_view { get; set; }
        public DbSet<parametermaster_view> parametermaster_view { get; set; }
        public DbSet<person> people { get; set; }
        public DbSet<tbllivemanuallossofentry> tbllivemanuallossofentries { get; set; }
    }
}
