//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Tata.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblemailreporttype
    {
        public tblemailreporttype()
        {
            this.recipientmailids = new HashSet<recipientmailid>();
            this.tblsendermailids = new HashSet<tblsendermailid>();
        }
    
        public int ERTID { get; set; }
        public string ReportType { get; set; }
        public string ReportDesc { get; set; }
        public int IsDeleted { get; set; }
        public System.DateTime CreatedOn { get; set; }
        public int CreatedBy { get; set; }
        public Nullable<System.DateTime> ModifiedOn { get; set; }
        public Nullable<int> ModifiedBy { get; set; }
    
        public virtual ICollection<recipientmailid> recipientmailids { get; set; }
        public virtual ICollection<tblsendermailid> tblsendermailids { get; set; }
    }
}
