//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Tata.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbllossescode
    {
        public tbllossescode()
        {
            this.tblbreakdowns = new HashSet<tblbreakdown>();
            this.tblemailescalations = new HashSet<tblemailescalation>();
            this.tblemailescalations1 = new HashSet<tblemailescalation>();
            this.tblemailescalations2 = new HashSet<tblemailescalation>();
            this.tblescalationlogs = new HashSet<tblescalationlog>();
            this.tbllivelossofentries = new HashSet<tbllivelossofentry>();
            this.tbllivelossofentryreps = new HashSet<tbllivelossofentryrep>();
            this.tbllivemanuallossofentryreps = new HashSet<tbllivemanuallossofentryrep>();
            this.tbllossofentries = new HashSet<tbllossofentry>();
            this.tblmanuallossofentries = new HashSet<tblmanuallossofentry>();
            this.tbllivemanuallossofentries = new HashSet<tbllivemanuallossofentry>();
        }
    
        public int LossCodeID { get; set; }
        public string LossCode { get; set; }
        public string LossCodeDesc { get; set; }
        public string MessageType { get; set; }
        public int LossCodesLevel { get; set; }
        public Nullable<int> LossCodesLevel1ID { get; set; }
        public Nullable<int> LossCodesLevel2ID { get; set; }
        public string ContributeTo { get; set; }
        public int IsDeleted { get; set; }
        public System.DateTime CreatedOn { get; set; }
        public int CreatedBy { get; set; }
        public Nullable<System.DateTime> ModifiedOn { get; set; }
        public Nullable<int> ModifiedBy { get; set; }
        public Nullable<int> EndCode { get; set; }
        public Nullable<System.DateTime> DeletedDate { get; set; }
    
        public virtual ICollection<tblbreakdown> tblbreakdowns { get; set; }
        public virtual ICollection<tblemailescalation> tblemailescalations { get; set; }
        public virtual ICollection<tblemailescalation> tblemailescalations1 { get; set; }
        public virtual ICollection<tblemailescalation> tblemailescalations2 { get; set; }
        public virtual ICollection<tblescalationlog> tblescalationlogs { get; set; }
        public virtual ICollection<tbllivelossofentry> tbllivelossofentries { get; set; }
        public virtual ICollection<tbllivelossofentryrep> tbllivelossofentryreps { get; set; }
        public virtual ICollection<tbllivemanuallossofentryrep> tbllivemanuallossofentryreps { get; set; }
        public virtual ICollection<tbllossofentry> tbllossofentries { get; set; }
        public virtual ICollection<tblmanuallossofentry> tblmanuallossofentries { get; set; }
        public virtual ICollection<tbllivemanuallossofentry> tbllivemanuallossofentries { get; set; }
    }
}
